# Generated by Django 4.0.4 on 2022-06-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='bio',
            field=models.TextField(default=None, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='img',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.TextField(max_length=4),
        ),
    ]
