# Generated by Django 4.0.4 on 2022-06-01 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_vehicletype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicletype',
            name='cars',
        ),
        migrations.AddField(
            model_name='car',
            name='vehicletype',
            field=models.ManyToManyField(to='main_app.vehicletype'),
        ),
    ]
