# Generated by Django 4.0.4 on 2022-06-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_car_bio_alter_car_img_alter_car_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='bio',
            field=models.TextField(default='Car Bio', max_length=500),
        ),
    ]
