# Generated by Django 4.0.4 on 2022-06-03 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_car_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyCar',
        ),
    ]
